packages:
  - "apps/*"
catalog:
  "@crossmint/client-sdk-react-ui": 1.19.21
  "@crossmint/client-sdk-window": "^1.0.0"
  "react": 19.0.0
  "react-dom": 19.0.0
  "@vercel/analytics": 1.5.0
  "clsx": 2.1.1
  "next": 15.2.3
  "tailwind-merge": 3.0.2
  "tw-animate-css": 1.2.4
  "viem": 2.27.0
  "zod": "3.22.4"